### ISSUE TITLE
Is git2u removed from iuscommunity repo?

### ISSUE THREAD

**Issue by julibarri1** [iusrepo/git224#3]
Running docker build and trying to set up ius rpm but receiving the following error:

Step 7/31 : RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm &&     yum install -y git2u &&     yum clean all  &&     rm -rf /etc/yum.repos.d/ius* &&     rm -rf /var/cache/yum
 ---> Running in 497b0768a268
Loaded plugins: fastestmirror, ovl
[91mCannot open: https://centos7.iuscommunity.org/ius-release.rpm. Skipping.
[0m[91mError: Nothing to do
[0mThe command '/bin/sh -c yum install -y https://centos7.iuscommunity.org/ius-release.rpm &&     yum install -y git2u &&     yum clean all  &&     rm -rf /etc/yum.repos.d/ius* &&     rm -rf /var/cache/yum' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
Time to scrape console output: 13 ms
Should send to SNS? Yes
Should send to Insights? No
Finished: FAILURE

I see where this repo "dropped off" before, did this happen again?

**Comment by julibarri1** [comment]
Tried http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-13.ius.centos7.noarch.rpm as noted here: https://www.certdepot.net/rhel7-how-to-install-the-ius-community-repository/

Same behavior.

**Comment by carlwgeorge** [comment]
The git2u pacakge was [renamed to git216](https://github.com/iusrepo/git216/issues/14), which was later [retired](https://github.com/iusrepo/announce/issues/19).  If you use IUS I highly recommend watching the [announce repository](https://github.com/iusrepo/announce) to be notified when packages are retired.

https://ius.io/faq#how-do-i-know-when-an-ius-package-is-being-retired
