### ISSUE TITLE
git 2.29.0 is available

### ISSUE THREAD

**Issue by nkadel** [iusrepo/git224#5]
git 2.29.0 is now available. I submitted a pull request to support it: I'm not sure how you'd want to publish that, perhaps as a new git229 repo? You're very welcome to the .spec file from my pull request for that repo.

**Comment by carlwgeorge** [comment]
You are correct, a git229 package would be a new package and a new repo.  Please follow the process for requesting a [new IUS package](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md).
