### ISSUE TITLE
git224 is out of date, git231 is available

### ISSUE THREAD

**Issue by nkadel** [iusrepo/git224#9]
The git 2.24 release is falling increasingly out of date. I've published a git 2.31 git repo, forked from your git224 repo at https://github.com/nkadel/nkadel-git231-srpm. It's passing my smoke testing, I hope you can accept it for IUS publication.

**Comment by carlwgeorge** [comment]
git224 is not out of date.  It is on the current https://github.com/git/git/releases/tag/v2.24.4 version.  Packaging newer versions that aren't 2.24.x would need to be done in a new package request, which has started in https://github.com/iusrepo/wishlist/issues/302.

**Comment by nkadel** [comment]
On Sat, Aug 7, 2021 at 11:55 AM Carl George ***@***.***>
wrote:

> git224 is not out of date. It is on the current
> https://github.com/git/git/releases/tag/v2.24.4 version. Packaging newer
> versions that aren't 2.24.x would need to be done in a new package request,
> which has started in iusrepo/wishlist#302
> <https://github.com/iusrepo/wishlist/issues/302>.
>
>
> The existence of a previous release in this github repo is *not*
indication that a release is current. Every git release *ever* is
accessible at https://github.com/git/git/releases/ . The repo is following
the consistent git supported model where every git tag *ever* is available
as a "release".

A new package request is just what I meant. I've published an updated
package configuration at https://github.com/nkadel/nkadel-git232-srpm , you
are more than welcome to it.

Nico Kadel-Garcia ***@***.***>

**Comment by carlwgeorge** [comment]
> The existence of a previous release in this github repo is *not* indication that a release is current.

I didn't claim it was.  I pointed you to the latest 2.24.x tag.  If/when the git project creates a 2.24.5 release, git224 will be updated to it.  That's how IUS works.  Please familiarize yourself with the IUS [naming scheme](https://ius.io/about#inline-with-upstream-stable).  git224 will never be updated to anything other than upstream 2.24.x versions.

> A new package request is just what I meant.

Then why are you still commenting on this closed issue?  Issues in this repo are only for the git224 package.  New packages requests go to the wishlist (where there is already an issue for this).

**Comment by nkadel** [comment]
On Sat, Aug 7, 2021 at 9:09 PM Carl George ***@***.***> wrote:

> The existence of a previous release in this github repo is *not*
> indication that a release is current.
>
> I didn't claim it was. I pointed you to the latest 2.24.x tag. If/when the
> git project creates a 2.24.5 release, git224 will be updated to it. That's
> how IUS works. Please familiarize yourself with the IUS naming scheme
> <https://ius.io/about#inline-with-upstream-stable>. git224 will never be
> updated to anything other than upstream 2.24.x versions.
>

If I may quote you:

    > git224 is not out of date. It is on the current
https://github.com/git/git/releases/tag/v2.24.4 version.

That is not the "current version" It's the most recent version of git 2.24.
git 2.32.0 is the "current" version of git.

> A new package request is just what I meant.
>
> Then why are you still commenting on this closed issue? Issues in this
> repo are only for the git224 package. New packages requests go to the
> wishlist (where there is already an issue for this).
>
Because you just said something  very misleading about what is a "current
version", and I want people to understand what a "current version" really
means. I could see describing the current git224 package as "latest
subversion of git 2.24". which is more verbose, but more precise.

**Comment by carlwgeorge** [comment]
What I said was not misleading, it was precise and correct.  Upstream 2.32.0 is *not* the current version for the git224 package.  The current upstream version for the git224 package is 2.24.4.  Therefore, the package is current and this issue is invalid, hence being closed.

You're being intentionally antagonistic and argumentative.  That behavior is not welcome in the IUS project.  I am banning you from the project.
